### ISSUE TITLE
Log spam:  [WRN 19:17:54.015] Can not play a disabled audio source 

### ISSUE THREAD

**Issue by OrbitalManeuvers** [zorg2044/BoringCrewServices#25] opened 2024-10-10 23:37 UTC
My log:
https://drive.google.com/file/d/1uwrqX5sS_o-gOOlHXHYk8T81Cq38PZxx/view?usp=sharing

Got a few MB of these before I noticed.

**Comment by OrbitalManeuvers** [comment] 2024-10-10 23:38
Oh I should add ... this is the latest release 4a, plus the changes from github post-release.

**Comment by zorg2044** [comment] 2024-10-11 07:54
can you narrow this down to a specific part on the craft?

**Comment by OrbitalManeuvers** [comment] 2024-10-13 18:59
I apologize, this took me a couple days to get to. Haven't been home at my regular computers.

After some investigation, this is a problem with the doghouses. It's reproducible for me in two ways.

During ascent, I can just press ESC to pause the sim, and then when it unpauses I get this message on each doghouse or at least there's just a few of them.

The other way is shown in the picture below. Under this configuration, pressing "H" to translate forward shows this message as long as you have the H key down. I believe I was using throttle when I noticed this the first time.

https://i.imgur.com/HNBakk3.png

Lemme know if this doesn't repro for you and I will look into it farther.

**Comment by OrbitalManeuvers** [comment] 2024-10-13 19:07
I'm just realizing when this first showed up. I decided to assign action group 1 to the top RCS and 2 to the bottom, so that I could easily disable the more powerful one for docking. Maybe that was the first time I had some of them disabled?

**Comment by zorg2044** [comment] 2024-10-14 05:07
Ok thanks. I'm also out of town for a bit, will need to dig into it when I get back

**Comment by zorg2044** [comment] 2024-10-26 14:44
Hmm, I am unable to reproduce this either with translation or fore by throttle.

**Comment by zorg2044** [comment] 2024-10-28 15:50
Ah yeah I can reproduce this thanks. I had tested with just Block A earlier. Its quite puzzling, looking into it though.

**Comment by zorg2044** [comment] 2024-10-29 11:01
Should be fixed now in main.

**Closed** 2024-10-29 11:01 UTC
Labels: bug

**Comment by OrbitalManeuvers** [comment] 2024-10-29 14:47
tested and confirmed fixed. ty!
